module.exports = {
    trueFalseArray : new Array(
        true,
        false
    ),

    jobTypeArray : new Array(
        "FULLTIME",
        "CONTRACT"
    ),

    jobTitlesArray : ["Application Support Analyst",
    "Architect",
    "Blockchain Developer",
    "Blockchain Analyst",
    "Blockchain Engineer",
    "Blockchain Architect",
    "Blockchain Administrator",
    "Blockchain Analyst",
    "Blockchain Consultant",
    "Blockchain Manager",
    "Blcockchain Tester",
    "Business Analayst",
    "Business Data Analyst",
    "Business Domain Architect",
    "Business Systems Analyst",
    "Corda Developer",
    "Corda Blockchain Administrator",
    "Corda Blockchain Architect",
    "Corda Blockchain Consultant",
    "Corda Blockchain Developer",
    "Corda Blockchain Manager",
    "DevOps Engineer",
    "Developer Golang",
    "Developer Solidity",
    "Developer JavaScript",
    "Enterprise Architect",
    "Ethereum Developer",
    "Ethereum Blockchain Administrator",
    "Ethereum Blockchain Architect",
    "Ethereum Blockchain Consultant",
    "Ethereum Blockchain Developer",
    "Ethereum Blockchain Manager",
    "Full Stack Blockchain Developer",
    "Full Stack Java Developer",
    "Functional Consultant",
    "Gradute",
    "Graduete Developer",
    "Graduate Junior Developer",
    "Graduate Recruitment Consultant",
    "Graduate Analyst",
    "Graduate Blockchain Developer",
    "Graduate Engineer",
    "Graduate Software Constultant",
    "Graduate Software Developer",
    "Graduate Consultant",
    "Graduate Business Analyst",
    "Graduate IT",
    "Graduate IT Supoport",
    "Head of Blockchain Development",
    "Head",
    "Head of Engineering",
    "Head of Technology",
    "Hardware Engineer",
    "Head of Architecture",
    "Help Desk Engineer",
    "Head of Services",
    "Hyperledger Specialist",
    "Hyperledger Fabric Developer",
    "Hyperledger Fabric Administrator",
    "Hyperledger Fabric Analyst",
    "Hyperledger Fabric Tester",
    "Hyperledger Sawtooth Specialist",
    "Hyperledger Sawtooth Developer",
    "Hyperledger Sawtooth Administrator",
    "Hyperledger Sawtooth Analyst",
    "Hyperledger Sawtooth Tester",
    "Hyperledger Project Manager",
    "Hyperledger Tester",
    "IBM Blockchain Administrator",
    "IBM Blockchain Architect",
    "IBM Blockchain Developer",
    "IBM Blockchain Manager",
    "Infrastructure Engineer",
    "IT Support Engineer",
    "IT Manager",
    "IT Project Manager",
    "Information Security Analyst",
    "Informatica Architect",
    "IoS Developer",
    "IT Business Analyst",
    "Infrastructure Architect",
    "Infrasturcture Manager",
    "Integration Developer",
    "IT Field Engineer",
    "Java Developer",
    "JavaScript Developer",
    "Junior PHP Developer",
    "Junior Developer",
    "Junior Developer C#",
    "Junior Java Developer",
    "Junior .Net Developer",
    "Junior JavaScript Developer",
    "Junior Front End Developer",
    "Junior Web Developer",
    "Junior Business Analyst",
    "Key Account Manager",
    "Key Account Executive",
    "Knowledge Manager",
    "Lead Engineer",
    "Lead Developer",
    "Lead",
    "Lead Software Engineer",
    "Lead Java Developer",
    "Linux Systems Administrator",
    "Lead Software Developer",
    "Linux Engingeer",
    "Lead Business Analyst",
    "Lead Consultant",
    "Lead DevOps Engineer",
    "Lead .Net Developer",
    "Lead UX Designer",
    "Lead Manager",
    "Manager Contract",
    "Manager",
    "Mobile Developer",
    "Marketing Executive",
    "Mobile App Developer",
    "Management Information Analyst",
    "Manager Blockchain",
    "Neo Developer",
    "Neo Blockchain Administrator",
    "Neo Blockchain Architect",
    "Neo Blockchain Consultant",
    "Neo Blockchain Developer",
    "Neo Blockchain Manager",
    "Network Engineer",
    "Network Architect",
    "Node.JS Developer",
    "Network Manager",
    "Network Consultant",
    "Network Security Consultant",
    "Node.JS Software Engineer",
    "Network Security Analyst",
    "New Business Executive",
    "On-Site Engineer",
    "Operations Manager",
    "Oracle Developer",
    "Oracle Blockchain Administrator",
    "Oracle Blockchain Architect",
    "Oracle Blockchain Consultant",
    "Oracle Blockchain Developer",
    "Oracle Blockchain Manager",
    "Office Manager",
    "Operations Analyst",
    "PHP Developer",
    "Project Manager",
    "Python Developer",
    "Product Manager",
    "Programme Manager",
    "Platform Engineer",
    "Project Manager Business",
    "Project Manager Software",
    "Partner",
    "Pre-Sales Consultant",
    "Product Analyst",
    "QA Engineer",
    "QA Manager",
    "QA Analyst",
    "QA Automation Tester",
    "QA Automation Engineer",
    "QA Test Analyst",
    "QA Tester",
    "QA Test Engineer",
    "QA Developer",
    "QA Lead",
    "Quality Inspector",
    "QA Assistant",
    "Quorum Developer",
    "Quorum Blockchain Administrator",
    "Quorum Blockchain Architect",
    "Quorum Blockchain Consultant",
    "Quorum Blockchain Developer",
    "Quorum Blockchain Manager",
    "React Developer",
    "Remote Developer",
    "Researcher",
    "Release Engineer",
    "Release Manager",
    "Release Analyst",
    "Resource Manager",
    "Resourcer",
    "Ripple Developer",
    "Ripple Blockchain Administrator",
    "Ripple Blockchain Architect",
    "Ripple Blockchain Consultant",
    "Ripple Blockchain Developer",
    "Ripple Blockchain Manager",
    "Software Developer",
    "Senior Blockchain Developer",
    "Senior Java Developer",
    "Senior Go Developer",
    "Senior Software Engineer",
    "Solution Architect",
    "Security Architect",
    "Service Desk Analyst",
    "Scrum Master",
    "Solidity Developer",
    "Software Engineer Blockchain",
    "Softwaer Engineer C++",
    "SQL Developer",
    "Systems Administrator",
    "Systems Architect",
    "Systems Engineer",
    "Team Lead",
    "Technical Architect",
    "Technical Project Manager",
    "Technical Specialist",
    "Technical Support Analyst",
    "Test Analyst",
    "Technical Consultant",
    "Technical Lead",
    "Test Manager",
    "Test Engineer",
    "Test Automation Engineer",
    "UX Designer",
    "UX Researcher",
    "User Researcher",
    "UI/UX Designer",
    "UX Developer",
    "UX Manager",
    "UX Architect",
    "VBA Developer",
    "Validation Engineer",
    "Visual Designer",
    "Validation Tester",
    "Web Analyst",
    "Web Developer",
    "Web Developer Blockchain",
    "Web Developer PHP",
    "Web Designer",
    "Web Operator",
    "Web Engineer",
    "Web Tester",
    "XML Developer"]
}